### ISSUE TITLE
Delete expired posts and upvotes from chain

### ISSUE THREAD

**Issue by shanev** [public-awesome/stakebird#75]

**Comment by JakeHartnell** [comment]
I believe this is needed for DevNet. Without it we get a `Consensus Failure` after we refund the post deposit for the second time (since the deposit was already refunded).

```
E[2020-07-30|15:03:55.967] CONSENSUS FAILURE!!!                         module=consensus err="0ufuel is smaller than 1000000ufuel: insufficient funds" stack="goroutine 182 [running]:\nruntime/debug.Stack(0xc00291a310, 0x1430ae0, 0xc002d20ca0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc000c83880, 0x1705378)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:617 +0x57\npanic(0x1430ae0, 0xc002d20ca0)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/public-awesome/stakebird/x/curating.EndBlocker.func1(0x1, 0xc002d231a0, 0x20, 0x20, 0xc002d231c0, 0x14, 0x20, 0xc002d231e0, 0x14, 0x20, ...)\n\t/home/meow/Dev/RocketSpace/stakebird/x/curating/abci.go:30 +0x7c6\ngithub.com/public-awesome/stakebird/x/curating/keeper.Keeper.IterateExpiredPosts(0x198caa0, 0xc000026b60, 0x19be8e0, 0xc000c85650, 0x19a6400, 0xc0000c4d80, 0x7f472410a2f0, 0xc000163180, 0x19be8e0, 0xc000c85650, ...)\n\t/home/meow/Dev/RocketSpace/stakebird/x/curating/keeper/post.go:185 +0x334\ngithub.com/public-awesome/stakebird/x/curating.EndBlocker(0x19a1480, 0xc000132010, 0x19bac60, 0xc002e108c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/meow/Dev/RocketSpace/stakebird/x/curating/abci.go:23 +0xc1\ngithub.com/public-awesome/stakebird/x/curating.AppModule.EndBlock(...)\n\t/home/meow/Dev/RocketSpace/stakebird/x/curating/module.go:142\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(0xc000182380, 0x19a1480, 0xc000132010, 0x19bac60, 0xc002e108c0, 0xa, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/meow/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200530180557-ba70f4d4dc2e/types/module/module.go:317 +0x208\ngithub.com/public-awesome/stakebird/app.(*StakebirdApp).EndBlocker(...)\n\t/home/meow/Dev/RocketSpace/stakebird/app/app.go:465\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000162640, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/meow/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200530180557-ba70f4d4dc2e/baseapp/abci.go:153 +0x12a\ngithub.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0004f5e60, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/abci/client/local_client.go:239 +0xff\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc000c3cf10, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/proxy/app_conn.go:77 +0x51\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x19a2040, 0xc000f72ba0, 0x19b2520, 0xc000c3cf10, 0xc000c328c0, 0x19bdce0, 0xc0004f6808, 0x6, 0xc000e2ea90, 0xa)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/state/execution.go:304 +0x6d4\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000247b90, 0xa, 0x0, 0xc000e2ea80, 0x6, 0xc000e2ea90, 0xa, 0xb, 0xc002afb840, 0x20, ...)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/state/execution.go:135 +0x17a\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000c83880, 0xc)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1459 +0x8f5\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000c83880, 0xc)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1377 +0x383\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0xc000c83880, 0x0, 0xc)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1312 +0x90\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000c83880, 0xc, 0x0)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1349 +0x61e\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000c83880, 0xc002dcadc0, 0x0, 0x0, 0xfb69f42e, 0x3bd47e701f8bbb2a, 0xc0025b0c00)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1891 +0xa39\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000c83880, 0xc002dcadc0, 0x0, 0x0, 0xc00291fb90, 0x249e110, 0x1707448)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1707 +0x67\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000c83880, 0x1978900, 0xc0004f7098, 0x0, 0x0)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:713 +0x525\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000c83880, 0x0)\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:664 +0x597\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/home/meow/go/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:335 +0x13a\n"
```
